project:
  type: website

website:
  # title: "🤔"
  title: Papers
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa solid house >}}"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto